export const TrConceptGroups = new Map()
TrConceptGroups.set("definition", {en: "Definition", ru: "Определение"})
TrConceptGroups.set("loop", {en: "Loops", ru: "Циклы"})
TrConceptGroups.set("bitwise", {en: "Bitwise operators", ru: "Побитовые операторы"})
TrConceptGroups.set("array", {en: "Arrays", ru: "Массивы"})

export const TrConcepts = new Map()
TrConcepts.set("constant", {en: "Сonstant", ru: "Константа"})
TrConcepts.set("variable", {en: "Variable", ru: "Переменная"})
TrConcepts.set("for", {en: "For loop", ru: "Цикл for"})
TrConcepts.set("bitwise-xor", {en: "XOR", ru: "XOR"})
TrConcepts.set("array-length", {en: "Array length"})
TrConcepts.set("array-add", {en: "Add element"})
TrConcepts.set("array-remove", {en: "Delete element"})
TrConcepts.set("array-includes", {en: "Element exists in array"})
TrConcepts.set("array-index-of", {en: "Element index"})

export const TrCodeDescriptions = new Map()
TrCodeDescriptions.set("javascript-variable-let", {en: "Block scope", ru: "С блочной областью видимости"})