export const TrConceptGroups = new Map()
TrConceptGroups.set("definition", {en: "Definition", ru: "Определение"})
TrConceptGroups.set("loop", {en: "Loops", ru: "Циклы"})
TrConceptGroups.set("bitwise", {en: "Bitwise operators", ru: "Побитовые операторы"})
TrConceptGroups.set("array", {en: "Arrays", ru: "Массивы"})

export const TrConcepts = new Map()
TrConcepts.set("constant", {en: "Сonstant", ru: "Константа"})
TrConcepts.set("variable", {en: "Variable", ru: "Переменная"})
TrConcepts.set("for", {en: "For loop", ru: "Цикл for"})
TrConcepts.set("bitwise-xor", {en: "XOR", ru: "XOR"})
TrConcepts.set("array-length", {en: "Array length"})
TrConcepts.set("array-add", {en: "Add element"})
TrConcepts.set("array-remove", {en: "Delete element"})
TrConcepts.set("array-includes", {en: "Element exists in array"})
TrConcepts.set("array-index-of", {en: "Element index"})

export const TrCodeDescriptions = new Map()
TrCodeDescriptions.set("javascript-variable-let", {en: "Block scope", ru: "С блочной областью видимости"})

export const TrInterface = new Map()
TrInterface.set("settings", {en: "Settings", ru: "Настройки"})
TrInterface.set("search", {en: "Search...", ru: "Поиск..."})
TrInterface.set("languages", {en: "Programming languages", ru: "Языки программирования"})
TrInterface.set("translation", {en: "Translation", ru: "Язык интерфейса"})
TrInterface.set("en", {en: "English", ru: "Английский"})
TrInterface.set("ru", {en: "Russian", ru: "Русский"})

export const TrLanguages = new Map()
TrLanguages.set("csharp", {en: "C#"})
TrLanguages.set("go", {en: "Go"})
TrLanguages.set("javascript", {en: "JavaScript"})